2023-05-16 13:08:39,536 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-16 13:16:55,261 [ERROR] export_data.export: An error occurred while exporting table data: No module named 'xlsxwriter' [line:68]
2023-05-16 13:16:55,262 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 13:16:55,262 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 13:19:43,909 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 13:19:43,910 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 14:00:03,836 [ERROR] export_data.export: An error occurred while exporting table data: No module named 'xlsxwriter' [line:68]
2023-05-16 14:00:03,837 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 14:00:03,839 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 14:04:17,658 [ERROR] export_data.export: An error occurred while exporting table data: No module named 'openpyxl' [line:68]
2023-05-16 14:04:17,660 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 14:04:17,660 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 14:06:18,031 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 14:06:18,032 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 14:13:04,801 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 14:13:04,806 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 14:18:32,642 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 14:18:32,642 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 14:21:53,874 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 14:21:53,875 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 14:30:03,451 [ERROR] export_data.export: An error occurred while exporting table data: At least one sheet must be visible [line:68]
2023-05-16 14:30:03,463 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 14:30:03,464 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 14:30:55,910 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 14:30:55,911 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 14:43:40,440 [INFO] export_data.export: Export operation completed. [line:72]
2023-05-16 14:43:40,440 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 18:21:17,285 [INFO] schedule_tasks.run: Export script stopped by user. [line:107]
2023-05-16 18:24:16,673 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-16 18:25:43,615 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 18:25:43,616 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 18:26:33,824 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 18:26:33,824 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 18:27:45,759 [INFO] schedule_tasks.schedule_exports: Export scheduled for profile data at 18:29 [line:55]
2023-05-16 18:27:45,759 [INFO] schedule_tasks.schedule_exports: Export scheduled for comments data at 18:29 [line:55]
2023-05-16 18:27:45,759 [INFO] schedule_tasks.schedule_exports: Export scheduled for profile data at 18:31 [line:55]
2023-05-16 18:27:45,759 [INFO] schedule_tasks.schedule_exports: Export scheduled for comments data at 18:31 [line:55]
2023-05-16 18:29:00,814 [DEBUG] __init__.run: Running job Job(interval=1, unit=days, do=export_table_data, args=('profile data', 'select * from profile_collection limit 10', 'xlsx'), kwargs={}) [line:692]
2023-05-16 18:29:05,181 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 18:29:05,181 [INFO] schedule_tasks.export_table_data: Data exported successfully! [line:73]
2023-05-16 18:29:05,181 [DEBUG] __init__.run: Running job Job(interval=1, unit=days, do=export_table_data, args=('comments data', 'select * from comment_collection limit 100', 'xlsx'), kwargs={}) [line:692]
2023-05-16 18:29:09,963 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 18:29:09,963 [INFO] schedule_tasks.export_table_data: Data exported successfully! [line:73]
2023-05-16 18:31:00,031 [DEBUG] __init__.run: Running job Job(interval=1, unit=days, do=export_table_data, args=('profile data', 'select * from profile_collection limit 10', 'xlsx'), kwargs={}) [line:692]
2023-05-16 18:31:00,102 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 18:31:00,102 [INFO] schedule_tasks.export_table_data: Data exported successfully! [line:73]
2023-05-16 18:31:00,102 [DEBUG] __init__.run: Running job Job(interval=1, unit=days, do=export_table_data, args=('comments data', 'select * from comment_collection limit 100', 'xlsx'), kwargs={}) [line:692]
2023-05-16 18:31:00,159 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 18:31:00,159 [INFO] schedule_tasks.export_table_data: Data exported successfully! [line:73]
2023-05-16 18:34:43,962 [INFO] schedule_tasks.schedule_exports: Export scheduled for comments data at 18:36 [line:55]
2023-05-16 18:36:00,010 [DEBUG] __init__.run: Running job Job(interval=1, unit=days, do=export_table_data, args=('comments data', 'select * from comment_collection limit 100', 'xlsx'), kwargs={}) [line:692]
2023-05-16 18:36:05,337 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 18:36:05,337 [INFO] schedule_tasks.export_table_data: Data exported successfully! [line:73]
2023-05-16 18:46:40,205 [INFO] schedule_tasks.schedule_exports: Export scheduled for comments data at 18:50 [line:55]
2023-05-16 19:04:17,007 [INFO] schedule_tasks.schedule_exports: Export scheduled for comments data at 17:34 [line:53]
2023-05-16 19:06:47,426 [INFO] schedule_tasks.schedule_exports: Export scheduled for comments data at 19:07 [line:53]
2023-05-16 19:07:00,521 [DEBUG] __init__.run: Running job Job(interval=1, unit=days, do=export_table_data, args=('comments data', 'select * from comment_collection limit 100', 'xlsx'), kwargs={}) [line:692]
2023-05-16 19:07:06,026 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 19:07:06,026 [INFO] schedule_tasks.export_table_data: Data exported successfully! [line:69]
2023-05-16 19:32:50,290 [INFO] schedule_tasks.schedule_exports: Export scheduled for comments data at 19:33 [line:54]
2023-05-16 19:33:00,301 [DEBUG] __init__.run: Running job Job(interval=1, unit=days, do=export_table_data, args=('comments data', 'select * from comment_collection limit 100', 'csv'), kwargs={}) [line:692]
2023-05-16 19:33:08,905 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 19:33:08,905 [INFO] schedule_tasks.export_table_data: Data exported successfully! [line:70]
2023-05-16 19:37:57,627 [INFO] schedule_tasks.schedule_exports: Export scheduled for comments data at 19:39 [line:54]
2023-05-16 20:01:28,294 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 20:01:28,294 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 20:05:08,104 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 20:05:08,104 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-16 20:07:36,923 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-16 20:07:36,923 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-17 13:56:22,737 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-17 13:56:42,442 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-17 13:56:42,442 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-17 15:13:44,350 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-17 15:13:49,516 [ERROR] db_functions.test_database_connection: Failed to connect to the database: 2005 (HY000): Unknown MySQL server host 'mrhehe' (8) [line:144]
2023-05-17 15:16:25,942 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-17 16:25:53,369 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-17 16:25:53,369 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-17 16:27:05,404 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-17 16:27:05,404 [INFO] engine.export_table_data: Data exported successfully! [line:18]
2023-05-17 16:27:22,585 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-17 16:29:06,259 [INFO] schedule_tasks.schedule_exports: Export scheduled for profile data at 16:29 [line:54]
2023-05-17 16:29:06,259 [INFO] schedule_tasks.schedule_exports: Export scheduled for comment at 16:29 [line:54]
2023-05-17 16:29:06,259 [INFO] schedule_tasks.schedule_exports: Export scheduled for profile data at 16:31 [line:54]
2023-05-17 16:29:06,259 [INFO] schedule_tasks.schedule_exports: Export scheduled for comment at 16:31 [line:54]
2023-05-17 16:31:00,335 [DEBUG] __init__.run: Running job Job(interval=1, unit=days, do=export_table_data, args=('profile data', 'select * from profile_collection limit 100', 'xlsx'), kwargs={}) [line:692]
2023-05-17 16:31:05,779 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-17 16:31:05,779 [INFO] schedule_tasks.export_table_data: Data exported successfully! [line:70]
2023-05-17 16:31:05,779 [DEBUG] __init__.run: Running job Job(interval=1, unit=days, do=export_table_data, args=('comment', 'select * from profile_collection limit 50', 'xlsx'), kwargs={}) [line:692]
2023-05-17 16:31:10,613 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-17 16:31:10,621 [INFO] schedule_tasks.export_table_data: Data exported successfully! [line:70]
2023-05-18 11:04:48,871 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-18 11:04:55,696 [ERROR] db_functions.test_database_connection: Failed to connect to the database: 2003 (HY000): Can't connect to MySQL server on 'localhost:5437' (10061) [line:147]
2023-05-18 11:14:20,103 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-18 11:15:23,712 [ERROR] db_functions.test_postgresql_connection: Failed to connect to the PostgreSQL database: invalid dsn: invalid connection option "db"
 [line:175]
2023-05-18 11:16:11,451 [ERROR] db_functions.test_postgresql_connection: Failed to connect to the PostgreSQL database: invalid dsn: invalid connection option "db"
 [line:175]
2023-05-18 11:17:58,686 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-18 11:19:03,839 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-18 11:34:14,057 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-18 13:53:57,341 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-18 14:30:38,226 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-18 14:32:35,383 [ERROR] db_functions.test_postgresql_connection: Failed to connect to the PostgreSQL database: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 3306 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 3306 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8) [line:110]
2023-05-18 18:50:30,207 [ERROR] db_functions.test_mysql_connection: Failed to connect to the database: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host '23*@meshreportingsvr.mysql.database.azure.com' (11003)
(Background on this error at: https://sqlalche.me/e/20/4xp6) [line:99]
2023-05-18 23:20:49,096 [ERROR] db_functions.test_mysql_connection: Failed to connect to the database: Can't load plugin: sqlalchemy.dialects:mysql.pymsql [line:99]
2023-05-18 23:22:42,982 [ERROR] db_functions.test_mysql_connection: Failed to connect to the database: No module named 'pymysql' [line:99]
2023-05-18 23:25:48,913 [ERROR] db_functions.test_mysql_connection: Failed to connect to the database: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '23*@meshreportingsvr.mysql.database.azure.com' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8) [line:99]
2023-05-18 23:29:52,216 [DEBUG] proactor_events.__init__: Using proactor: IocpProactor [line:629]
2023-05-18 23:31:12,630 [INFO] export_data.export: Export operation completed. [line:82]
2023-05-18 23:31:12,630 [INFO] engine.export_table_data: Data exported successfully! [line:18]
